language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
    - pip install coveralls
install: "pip install -r requirements.txt"
# command to run tests
script: cd tests/ && py.test
after_success:
    - coveralls
