language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
notifications:
    email: false
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - nosetests --with-coverage
after_success:
    - coveralls
